### ISSUE TITLE
Documento DRS

### ISSUE THREAD

**Issue by Ariadnamonserrat10** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-buscadores-de-datos#1]
* Roldan Uriel Arcadio Avila 
* Pedro Garcia Garcia
* Ariadna Monserrat Lopez Aparicio

https://github.com/SistemasTecTlaxiaco/Academy/wiki

**Comment by EdgarExa** [comment]
25 de 25

**Comment by josealfredo79** [comment]
bien hecho y revisado..
